swagger: "2.0"

info:
  description: "This file is dedicated for storing Yelp Clone server API spec documentation."
  version: "1.0.0"
  title: "Yelp Clone"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3005"
basePath: "/api/v1"
tags:
- name: "restaurants"
  description: "List of all restaurants"
  externalDocs:
    description: "Find out more"
    url: "http://localhost:3005"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more"
    url: "http://localhost:3005"
schemes:
- "https"
- "http"
paths:
  /restaurants:
    get:
      summary: "Retrieve a list of all restaurants in database"
      description: ""
      parameters:
      - in: ""
        schema:
          $ref: ""
      responses:
        "404":
          description: "Not found"